name: libre_translate
description: A simple wrapper around the LibreTranslate API.
version: 1.0.0
repository: https://github.com/abitofevrything/libre_translate-dart

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
